name: 0.a.build-push-docker-nifi

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  USERNAME: informatievlaanderen
  BASE_IMAGE_TAG: 17-slim-buster
  NIFI_VERSION: 1.17.0
  DISTRO_PATH: 1.17.0
  TARGET_IMAGE_TAG: 1.17.0-jdk17
  NIFI_IMAGE: nifi
  NIFI_DOCKER_IMAGE_NAME: ghcr.io/informatievlaanderen/nifi
  NIFI_DOCKER_IMAGE_VERSION: 1.17.0-jdk17
  SINGLE_USER_CREDENTIALS_USERNAME: ${{ secrets.SINGLE_USER_CREDENTIALS_USERNAME }}
  SINGLE_USER_CREDENTIALS_PASSWORD: ${{ secrets.SINGLE_USER_CREDENTIALS_PASSWORD }}

jobs:
  job-build-push-docker-nifi:
    name: Build and push VSDS NiFi docker image
    runs-on: ubuntu-latest
    steps:
      - id: check_registry
        name: Check registry for existing VSDS NiFi docker image
        run: |
          TOKEN=$(echo ${{ secrets.GITHUB_TOKEN }} | base64)
          IMAGE_PRESENT=$(curl -H "Authorization: Bearer ${TOKEN}" -X GET https://${{ env.REGISTRY }}/v2/${{ env.USERNAME }}/${{ env.NIFI_IMAGE }}/tags/list | jq '.tags | any(. == "${{ env.NIFI_DOCKER_IMAGE_VERSION }}")')
          if [[ $IMAGE_PRESENT == "true" ]]; then
            echo "::set-output name=result::1"
          else
            echo "::set-output name=result::0"
          fi
      - name: Checkout repository
        uses: actions/checkout@v3
        if: steps.check_registry.outputs.result != 1
      - name: Set up Docker Buildx
        if: steps.check_registry.outputs.result != 1
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        if: steps.check_registry.outputs.result != 1
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: Informatievlaanderen
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build NiFi JDK17 Docker image
        if: steps.check_registry.outputs.result != 1
        run: |
          echo ENVIRONMENT
          echo BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
          echo NIFI_VERSION: ${NIFI_VERSION}
          echo TARGET_IMAGE_TAG: ${NIFI_VERSION-jdk17}
          echo NIFI_DOCKER_IMAGE_NAME: ${NIFI_DOCKER_IMAGE_NAME}
          echo NIFI_DOCKER_IMAGE_VERSION: ${NIFI_DOCKER_IMAGE_VERSION}
          curl -L https://github.com/apache/nifi/archive/refs/tags/rel/nifi-${NIFI_VERSION}.tar.gz | tar -zxv --strip-components=2 nifi-rel-nifi-${NIFI_VERSION}/nifi-docker/dockerhub/
          sed -i 's/xmlstarlet procps$/xmlstarlet procps curl unzip/' dockerhub/Dockerfile
          docker build --build-arg IMAGE_TAG="${BASE_IMAGE_TAG}" --build-arg NIFI_VERSION="${NIFI_VERSION}" --build-arg DISTRO_PATH="${DISTRO_PATH}" -t "${NIFI_DOCKER_IMAGE_NAME}:${NIFI_DOCKER_IMAGE_VERSION}" -f dockerhub/Dockerfile dockerhub/
          docker image push ${NIFI_DOCKER_IMAGE_NAME}:${NIFI_DOCKER_IMAGE_VERSION}
