name: 2.c.merge_push-docker-workbench-nifi

on:
  workflow_run:
    workflows: [2.b.merge_push-docker-client-cli]
    types: [completed]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  NIFI_DOCKER_IMAGE_VERSION: 1.17.0-jdk17
  LDES_NIFI_DOCKER_IMAGE_NAME: ghcr.io/informatievlaanderen/ldes-workbench-nifi
  SINGLE_USER_CREDENTIALS_USERNAME: ${{ secrets.SINGLE_USER_CREDENTIALS_USERNAME }}
  SINGLE_USER_CREDENTIALS_PASSWORD: ${{ secrets.SINGLE_USER_CREDENTIALS_PASSWORD }}

jobs:
  job-push-docker-workbench-nifi:
    name: Push LDES Client CLI docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: set release date
        run: |
          echo "BUILD_DATE=$(date +'%Y%m%dT%H%M%S')" >> ${GITHUB_ENV}
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: Informatievlaanderen
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 2.a.merge_push-maven-packages.yml
          workflow_conclusion: success
          path: ./ldes-client-wrappers/ldes-client-wrappers-nifi/ldes-workbench-nifi
          name: ldes-nar
      - name: Build LDES Workbench NiFi Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./ldes-client-wrappers/ldes-client-wrappers-nifi/ldes-workbench-nifi
          push: true
          tags: |
            ${{ env.LDES_NIFI_DOCKER_IMAGE_NAME }}:${{ env.BUILD_DATE }}
          build-args: |
            NIFI_DOCKER_IMAGE_VERSION=${{ env.NIFI_DOCKER_IMAGE_VERSION }}
